### ISSUE TITLE
Pasting Images

### ISSUE THREAD

**Issue by buraddo** [iionly/Elgg_1.8_extended_tinymce#2]
tried changing file views/default/js/extended_tinymce.php
variable
paste_data_images: true (deactivate/activated plug, flushed cache and ran upgrade script)
but still images are stripped in the paste.
Does work with version
Elgg_1.8_extended_tinymce_v3.5.7_r18.zip
no modifications done.

**Comment by iionly** [comment]
Closing due to long time without activity.
